# Generated by Django 3.2 on 2023-07-24 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'permissions': [('look_a_page', 'can get this page message')],
            },
        ),
        migrations.CreateModel(
            name='Bpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'permissions': [('look_b_page', 'can get this page message')],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='用戶名')),
                ('age', models.IntegerField(default=0, verbose_name='年齡')),
                ('info', models.TextField(verbose_name='個人訊息')),
                ('sex', models.CharField(choices=[('Male', '男'), ('Female', '女')], default='Male', max_length=6, verbose_name='性別')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2023, 7, 24, 15, 13, 38, 248879), verbose_name='時間')),
            ],
            options={
                'verbose_name': '用戶表',
                'verbose_name_plural': '用戶表',
            },
        ),
    ]
