# Generated by Django 3.2.16 on 2023-02-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='dame',
            field=models.IntegerField(default=1),
        ),
    ]
