# Generated by Django 3.2 on 2023-07-25 00:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_auto_20230725_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'permissions': [('look_a_page', 'can get this page message')],
            },
        ),
        migrations.CreateModel(
            name='Bpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'permissions': [('look_b_page', 'can get this page message')],
            },
        ),
        migrations.AlterField(
            model_name='test',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 8, 7, 47, 94335), verbose_name='時間'),
        ),
    ]
