# Generated by Django 3.2.16 on 2023-02-04 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_remove_test_dame'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': '用戶表'},
        ),
        migrations.AddField(
            model_name='test',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 4, 9, 0, 38, 497899)),
        ),
        migrations.AddField(
            model_name='test',
            name='info',
            field=models.TextField(default=2, verbose_name='個人訊息'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='sex',
            field=models.CharField(choices=[('Male', '男'), ('Female', '女')], default='Male', max_length=6),
        ),
        migrations.AlterField(
            model_name='test',
            name='age',
            field=models.IntegerField(default=0, verbose_name='年齡'),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=20, verbose_name='用戶名'),
        ),
    ]
