# Generated by Django 3.2.16 on 2023-02-04 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_auto_20230204_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'permissions': [('look_a_page', 'can get this page message')],
            },
        ),
        migrations.CreateModel(
            name='Bpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'permissions': [('look_b_page', 'can get this page message')],
            },
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': '用戶表', 'verbose_name_plural': '用戶表'},
        ),
        migrations.AlterField(
            model_name='test',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 4, 15, 42, 56, 955414), verbose_name='時間'),
        ),
        migrations.AlterField(
            model_name='test',
            name='sex',
            field=models.CharField(choices=[('Male', '男'), ('Female', '女')], default='Male', max_length=6, verbose_name='性別'),
        ),
    ]
