# Generated by Django 3.2 on 2023-07-25 00:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appclass', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training_cycle',
            old_name='my_string',
            new_name='progress',
        ),
        migrations.AddField(
            model_name='training_cycle',
            name='finish_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 8, 7, 22, 307104), verbose_name='時間'),
        ),
    ]
