# Generated by Django 3.2 on 2023-07-25 00:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appclass', '0002_auto_20230725_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training_cycle',
            name='finish_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 8, 7, 47, 93339), verbose_name='時間'),
        ),
    ]
